{
  "name": "XiaodingNode",
  "website": "https://twitter.com/xiaoding318",
  "description": "XiaodingNode is a trusted PoS validater and shares accessible node installation guides for beginners and expers alike. ",
  "logo": "https://europe1.discourse-cdn.com/standard20/uploads/starknet1/optimized/3X/9/1/912a9a87483d2957269c39bfbf6f1b25b986bf10_2_144x144.png",
  "twitter": "https://twitter.com/xiaoding318"
}
