{
  "name": "XiaodingNode",
  "website": "https://twitter.com/xiaoding318",
  "description": "XiaodingNode is a trusted PoS validater and shares accessible node installation guides for beginners and expers alike. ",
  "logo": "http://5b0988e595225.cdn.sohucs.com/images/20190415/d88505b0cf964935a693d9818c3d6e8a.jpeg",
  "twitter": "https://twitter.com/xiaoding318"
}
