{
  "name": "XiaodingNode",
  "website": "https://twitter.com/xiaoding318",
  "description": "XiaodingNode is a trusted PoS validater and shares accessible node installation guides for beginners and expers alike. ",
  "logo": "https://image.baidu.com/search/detail?ct=503316480&z=0&ipn=d&word=xiaoding&step_word=&hs=0&pn=83&spn=0&di=41943041&pi=0&rn=1&tn=baiduimagedetail&is=0%2C0&istype=0&ie=utf-8&oe=utf-8&in=&cl=2&lm=-1&st=undefined&cs=3101633840%2C1622181269&os=2114016902%2C3176342075&simid=65218772%2C630864795&adpicid=0&lpn=0&ln=1857&fr=&fmq=1705680710109_R&fm=&ic=undefined&s=undefined&hd=undefined&latest=undefined&copyright=undefined&se=&sme=&tab=0&width=undefined&height=undefined&face=undefined&ist=&jit=&cg=&bdtype=10&oriquery=&objurl=https%3A%2F%2Ftvax3.sinaimg.cn%2Fcrop.0.0.996.996.1024%2Fa3ebd9b1ly8fri9udgeebj20ro0ro3zi.jpg",
  "twitter": "https://twitter.com/xiaoding318"
}
